### ISSUE TITLE
One more quickstart/sample

### ISSUE THREAD

**Issue by lukekim** [spiceai/quickstarts#17]

**Comment by iudex-** [comment]
Could it be one demonstrating prediction? :blush: 

Or am I lost  and prediction isn't something the project aims to do? 

I understand that [predefined actions](https://docs.spiceai.org/reference/pod/#actions) are the "output", but couldn't something like this work?
``` yaml
dataspaces:
  - from: local
    name: portfolio
    fields:
      - name: prediction
    actions:
      dec: |
        prediction -= 1
      inc: |
        prediction += 1
```
